Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TestTaskApplication.Data;
using TestTaskApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TestTaskApplication.Controllers
{
    public class DepartmentController : Controller
    {

        private UnitOfWork _unitOfWork;
        public DepartmentController(UnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }


        public IActionResult Index()
        {
            List<Department> departments;
            try
            {
                departments =  _unitOfWork.DepartmentRepository.GetAll();
            }
            catch (Exception e) { ModelState.AddModelError("", e.Message); return View(); }

            return View(departments);

        }

        public ActionResult Details(int id)
        {
            return View();
        }

        
    }
}

Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TestTaskApplication.Data;
using TestTaskApplication.Models;


namespace TestTaskApplication.Controllers
{
    public class EmployeeController : Controller
    {
        UnitOfWork _unit;

        public EmployeeController(UnitOfWork unitOfWork)
        {
            _unit = unitOfWork;
        }
        
        public IActionResult Index()
        {
            List<Employee> employees;
            try
            {
                employees = _unit.EmployeeRepository.GetAll();
            }
            catch (Exception e) { 
                ModelState.AddModelError("", e.Message); 
                return View(); }
            if (employees != null)
            {
                foreach(Employee employee in employees)
                {
                    employee.Department = _unit.DepartmentRepository.GetById(employee.DepartmentID);
                }
            }
            return View(employees);
        }


        public IActionResult ShowByDepartmentId(Guid id)
        {
            
            List<Employee> employees;
            try
            {
                employees = _unit.EmployeeRepository.GetByDepartmentId(id);
            }
            catch (Exception e) { 
                ModelState.AddModelError("", e.Message); return View(); 
            }
            foreach (Employee employee in employees)
            {
                employee.Department = _unit.DepartmentRepository.GetById(employee.DepartmentID);
            }
            return View("Index", employees);
        }

        
        public IActionResult Create()
        {
            ViewBag.Date = DateTime.Now;
            ViewBag.SelectList = GetDepartmentsSelectList();
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Employee employee)
        {
            
            if (ModelState.IsValid)
            {
                try
                {
                    
                    _unit.EmployeeRepository.Create(employee);
                }
                catch (Exception e) { 
                    ModelState.AddModelError("", e.Message);
                    List<Department> departments = _unit.DepartmentRepository.GetAll();
                    SelectList selectList = new SelectList(departments, nameof(Department.ID), nameof(Department.Name));
                    ViewBag.SelectList = selectList;
                    return View(employee); 
                }
 
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Date = DateTime.Now;
                ViewBag.SelectList = GetDepartmentsSelectList();
                return View(employee);
            }
        }

       
        public IActionResult Edit(int id)
        {
            Employee? employee = _unit.EmployeeRepository.GetById((decimal)id);
            if (employee == null)
            {
                ModelState.AddModelError("", "User with such id is not found");
                return View("Index");
            }
            ViewBag.SelectList = GetDepartmentsSelectList();
            return View(employee);
        }

        private SelectList GetDepartmentsSelectList()
        {
            List<Department> departments = _unit.DepartmentRepository.GetAll();
            SelectList selectList = new SelectList(departments, nameof(Department.ID), nameof(Department.Name));
            return selectList;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Employee employee)
        {
            if (ModelState.IsValid) {

                try
                {
                    
                    _unit.EmployeeRepository.Update(employee);
                }
                catch (Exception e) {
                    ModelState.AddModelError("", e.Message); 
                    ViewBag.SelectList = GetDepartmentsSelectList();
                    return View(employee); 
                }
                
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.SelectList = GetDepartmentsSelectList();
                return View(employee);
            }
        }

        
     
        public IActionResult Delete(int id)
        {
            try
            {
                _unit.EmployeeRepository.Delete((decimal)id);
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", e.Message);
                return View();
            }
            return RedirectToAction("Index");
        }
    }
   
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ERP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ERP</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>